name: Release and Deploy Workflow

on:
  push:
    branches:
      - main

permissions:
  contents: write
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build for production
        run: npm run build

      - name: Config Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Bump version
        run: |
          # Bump version without creating a git tag
          npm version patch --no-git-tag-version

          VERSION=$(node -p "require('./package.json').version")

          # Stage all changes
          git stage -A

          # Commit version change
          git commit -m "Bump version to $VERSION [skip ci]"


          # Fetch origin
          git fetch origin

          # # Create release branch with tag
          # git checkout -b releases/v$VERSION
          # git tag -a "v$VERSION" -m "Release version $VERSION"

          # git push origin releases/v$VERSION
          # git push origin --tags
          git push origin main

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/personal-website/browser
          publish_branch: releases/build-artifacts
