name: Release Workflow

on:
  push:
    branches:
      - release

permissions:
  contents: write
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build for production
        run: npm run build --omit-dev

      - name: Config Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Tag version
        id: tag_version
        run: |
          # Bump version without creating a git tag
          npm version patch --no-git-tag-version

          VERSION=$(node -p "require('./package.json').version")

          # Stage all changes
          git stage -A

          # Commit version change
          git commit -m "Bump version to $VERSION"

          # Tag version

          # Fetch origin
          git fetch origin

          # Create release branch with tag
          git checkout -b releases/v$VERSION
          git tag -a "v$VERSION" -m "Release version $VERSION"

          # Push changes
          git push origin release
          # git push origin "v$VERSION"
          git push origin releases/v$VERSION
          git push origin --tags

      - name: Merge release into main
        run: |
          git fetch origin main
          git checkout main
          git pull origin main
          git merge release
          git push origin main

      - name: Delete release branch
        run: |
          git push origin --delete release
